name: spiralnegative
description: a glitch in your system
meta_description: spiralnegative
github: https://github.com/spiralnegative

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: http://spiralnegative.space
gems: [jekyll-paginate]
plugins:
  - jekyll-feed

# Details for the RSS feed generator
url:            http://spiralnegative.space
author:         Monica G.
bio:            Nature lover, software engineer, wannabe baker, tea drinker, cyberpunk enthusiast. INFJ ğŸ‡
permalink: /:title.html
